// Code generated by genservices. DO NOT EDIT.
package rbxweb

// Services is the list of implemented Roblox Web APIs
type Services struct {
	GamesV1          *GamesServiceV1
	ThumbnailsV1     *ThumbnailsServiceV1
	UsersV1          *UsersServiceV1
	AuthV2           *AuthServiceV2
	ClientSettingsV2 *ClientSettingsServiceV2
	AuthTokenV1      *AuthTokenServiceV1
}

func (c *Client) setServices() {
	c.GamesV1 = (*GamesServiceV1)(&c.common)
	c.ThumbnailsV1 = (*ThumbnailsServiceV1)(&c.common)
	c.UsersV1 = (*UsersServiceV1)(&c.common)
	c.AuthV2 = (*AuthServiceV2)(&c.common)
	c.ClientSettingsV2 = (*ClientSettingsServiceV2)(&c.common)
	c.AuthTokenV1 = (*AuthTokenServiceV1)(&c.common)
}
