package thumbnails

// ReturnPolicy represents an unknown property of a thumbnail.
type ReturnPolicy string

const (
	PlaceHolder        ReturnPolicy = "PlaceHolder" // Default
	AutoGenerated      ReturnPolicy = "AutoGenerated"
	ForceAutoGenerated ReturnPolicy = "ForceAutoGenerated"
)

// ThumbnailFormat represents the image format of a thumbnail.
type ThumbnailFormat string

const (
	Png  ThumbnailFormat = "Png"
	Jpeg ThumbnailFormat = "Jpeg"
)

// ThumbnailState represents the current asset state of a thumbnail.
type ThumbnailState string

const (
	Error                  ThumbnailState = "Error"
	Completed              ThumbnailState = "Completed"
	InReview               ThumbnailState = "InReview"
	Pending                ThumbnailState = "Pending"
	Blocked                ThumbnailState = "Blocked"
	TemporarilyUnavailable ThumbnailState = "TemporarilyUnavailable"
)

// Thumbnail implements the ThumbnailResponse API Model.
type Thumbnail struct {
	TargetID int64          `json:"targetId"`
	State    ThumbnailState `json:"state"`
	ImageURL string         `json:"imageUrl"`
	Version  string         `json:"version"`
}
